// <auto-generated />
using BearcatBites.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BearcatBites.Migrations
{
    [DbContext(typeof(BearcatBitesContext))]
    partial class BearcatBitesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.26");

            modelBuilder.Entity("BearcatBites.Models.FoodItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Restaurant")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("FoodItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A Cincinnati classic — a hot dog smothered in Cincinnati-style chili and topped with a mound of shredded cheddar cheese. The perfect blend of savory and cheesy in every bite.",
                            ImagePath = "Screenshot 2026-04-22 220535.png",
                            Name = "Skyline Cheese Coney",
                            Restaurant = "Skyline Chili",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Description = "A hearty Cincinnati-born breakfast sandwich featuring crispy goetta (pork and oat sausage), a fried egg, and melted cheese on a fresh-baked Belgian waffle bun.",
                            ImagePath = "Screenshot 2026-04-22 220737.png",
                            Name = "Goetta Breakfast Sandwich",
                            Restaurant = "Taste of Belgium",
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Description = "Fresh rice paper rolls packed with shrimp, vermicelli, crisp lettuce, cucumber, and herbs. Served with a rich house-made peanut dipping sauce.",
                            ImagePath = "Screenshot 2026-04-22 220757.png",
                            Name = "Vietnamese Spring Rolls (Gỏi Cuốn)",
                            Restaurant = "Pho Lang Thang",
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            Description = "Classic Taiwanese brown sugar milk tea loaded with chewy tapioca pearls. Rich, creamy, and just sweet enough — a beloved Cincinnati staple for boba fans.",
                            ImagePath = "Screenshot 2026-04-22 220831.png",
                            Name = "Boba Milk Tea",
                            Restaurant = "Tea n Bowl",
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            Description = "A beautifully balanced espresso drink made with locally sourced espresso, oat milk, and a house-made lavender syrup. Floral, smooth, and perfect any time of day.",
                            ImagePath = "Screenshot 2026-04-22 220852.png",
                            Name = "Lavender Oat Latte",
                            Restaurant = "Deeper Roots Coffee",
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            Description = "A thick and refreshing Indian yogurt-based drink blended with ripe Alphonso mango, a pinch of cardamom, and a hint of rose water. Cool and tropical in every sip.",
                            ImagePath = "Screenshot 2026-04-22 220912.png",
                            Name = "Mango Lassi",
                            Restaurant = "Ambar India Restaurant",
                            Type = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
